INSERT INTO participantes VALUES ('Carlitos', 'Arsenal') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Carlitos', 'Galatasaray') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Carlitos', 'Newcastle') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Carlitos', 'Lech Poznan') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Carlitos', 'Mainz') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Carlitos', 'Samsunspor') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Carlitos', 'Brann') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Carlitos', 'Nottingham') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Carlitos', 'Stuttgart') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Edwin', 'PSV') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Edwin', 'Qarabag') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Edwin', 'Real Madrid') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Edwin', 'Legia') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Edwin', 'Omonia') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Edwin', 'Shamrock Rovers') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Edwin', 'Bologna') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Edwin', 'Feyenoord') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Edwin', 'Malmo FF') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Enrique', 'Ajax') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Enrique', 'Atl. Madrid') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Enrique', 'Pafos') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Enrique', 'AEK Athens') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Enrique', 'Breidablik') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Enrique', 'Sigma Olomouc') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Enrique', 'Braga') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Enrique', 'FCSB') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Enrique', 'Salzburg') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Esteban', 'Ath Bilbao') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Esteban', 'Bayern Munich') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Esteban', 'Bodo/Glimt') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Esteban', 'AEK Larnaca') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Esteban', 'AZ Alkmaar') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Esteban', 'Shakhtar Donetsk') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Esteban', 'Basel') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Esteban', 'Lille') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Esteban', 'Plzen') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Farit', 'Benfica') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Farit', 'Dortmund') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Farit', 'Slavia Prague') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Farit', 'Lausanne') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Farit', 'SK Rapid') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Farit', 'Univ. Craiova') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Farit', 'Din. Zagreb') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Farit', 'Ludogorets') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Farit', 'Rangers') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Felipe', 'Kairat Almaty') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Felipe', 'Liverpool') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Felipe', 'Napoli') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Felipe', 'Aberdeen') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Felipe', 'Hamrun') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Felipe', 'Rijeka') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Felipe', 'Celta Vigo') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Felipe', 'Genk') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Felipe', 'Utrecht') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('John', 'Chelsea') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('John', 'Eintracht Frankfurt') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('John', 'Sporting CP') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('John', 'Hacken') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('John', 'Celje') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('John', 'Sparta Prague') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('John', 'Panathinaikos') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('John', 'Betis') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('John', 'Freiburg') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Loquito', 'FC Copenhagen') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Loquito', 'Manchester City') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Loquito', 'Marseille') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Loquito', 'Fiorentina') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Loquito', 'KuPS') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Loquito', 'Shkendija') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Loquito', 'Maccabi Tel Aviv') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Loquito', 'Midtjylland') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Loquito', 'AS Roma') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Pabón', 'Atalanta') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Pabón', 'Olympiacos Piraeus') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Pabón', 'PSG') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Pabón', 'Jagiellonia') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Pabón', 'Lincoln Red Imps') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Pabón', 'Noah') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Pabón', 'Lyon') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Pabón', 'PAOK') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Pabón', 'Sturm Graz') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Saulo', 'Bayer Leverkusen') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Saulo', 'Tottenham') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Saulo', 'Royale Union SG') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Saulo', 'Rakow') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Saulo', 'Rayo Vallecano') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Saulo', 'Strasbourg') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Saulo', 'Aston Villa') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Saulo', 'Ferencvaros') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Saulo', 'Young Boys') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Víctor', 'Barcelona') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Víctor', 'Monaco') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Víctor', 'Villarreal') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Víctor', 'Crystal Palace') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Víctor', 'Dyn. Kyiv') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Víctor', 'Slovan Bratislava') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Víctor', 'Celtic') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Víctor', 'Fenerbahce') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Víctor', 'G.A. Eagles') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Zoque', 'Club Brugge KV') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Zoque', 'Inter') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Zoque', 'Juventus') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Zoque', 'Drita') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Zoque', 'Shelbourne') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Zoque', 'Zrinjski') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Zoque', 'Nice') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Zoque', 'FC Porto') ON CONFLICT DO NOTHING;
INSERT INTO participantes VALUES ('Zoque', 'Crvena zvezda') ON CONFLICT DO NOTHING;
